services:
  gateway:
    build:
      dockerfile: services/gateway/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    links:
      - database
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/gateway/healthchecker || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 3

  client:
    build:
      dockerfile: services/clients/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      gateway:
        condition: service_healthy
    links:
      - database
    env_file:
      - .env

  products:
    build:
      dockerfile: services/products/Dockerfile
    ports:
      - 8001:8001
    depends_on:
      gateway:
        condition: service_healthy
    links:
      - database
    env_file:
      - .env

  favorite_products:
    build:
      dockerfile: services/favorite_products/Dockerfile
    ports:
      - 8002:8002
    depends_on:
      gateway:
        condition: service_healthy
    links:
      - database
    env_file:
      - .env

  database:
    image: mysql:8.0
    ports:
        - "3306:3306"
    restart: always
    hostname: luizalabsdb
    env_file:
      - .env
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./database/db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
        timeout: 20s
        retries: 10

  rabbit:
    image: rabbitmq:4-management
    restart: on-failure
    hostname: rabbit
    ports:
        - '5672:5672'
        - '15672:15672'
    env_file:
      - .env

volumes:
  database: